name: Maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Javadoc with Maven
        run: mvn --batch-mode --update-snapshots javadoc:javadoc
      - name: Check style with Maven
        run: mvn --batch-mode --update-snapshots checkstyle:check
